### ISSUE TITLE
Описание вариантов входных данных функции

### ISSUE THREAD

**Issue by NikomSol** [NikomSol/MCML-Integrating-Sphere#1]
Где описать доступные моды?
Т.е. условно на вход функции можно подавать такие-то варианты переменной - там и писать?
Если каждый вариант переменной отправляет к новой функции - что делает новая функция писать именно в ней?

**Comment by VulpesCorsac** [comment]
Не совсем понял, если честно, пример проблемы в студию (:

**Comment by NikomSol** [comment]
В мейне пользователь пишет:
cnf = {"mode": "Surface"}

И пошло оно дальше:
MCML(cnf)

Который вызывает: 
parse_mode(cnf)

Который вызывает:
parse_mode_generator(cnf)

В котором уже мы проверяем что за мод и не написано ли в cnf хрень.

Едем дальше parse_mode_generator(cnf)
Вызывает условно функцию get_surface_generator, которая уже отвечает за то, что дальше будет происходить в соответствии с заданным модом.

Вопрос 1: в документации к какой функции описать возможные варианты входа?
Вопрос 2: где описать то, что мы получим если зададим данный мод?

**Comment by VulpesCorsac** [comment]
Когда ты удёшь от словарей, то описание типа будет уже в самом enum class и дальше можно будет просто писать в аннотации - "настройки"
