### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by NikomSol** [NikomSol/MCML-Integrating-Sphere#11]
где писать туду?
хотелось бы, чтобы и в конкретном месте кода отображалось (как-то подсвечиваясь) и в каком-то одном месте кучкой
либо в одном месте кучкой с указанием на то в какой части кода все это делать

**Comment by VulpesCorsac** [comment]
Можешь в readme.md вполне. Но пока файлов мало, можно найти TODO и поиском по проекту. Не уверен, что для пайтона есть что-то, что само их соберёт (но, возможно, я просто не знаю, поищу на досуге)

**Comment by NikomSol** [comment]
Я нашел, как в vs code собирать все в одном месте то, что по тексту разбросано
Если нет у тебя отдельной потребности, то можно не искать
