### ISSUE TITLE
Выход за границу образца

### ISSUE THREAD

**Issue by NikomSol** [NikomSol/MCML-Integrating-Sphere#18]
У меня сейчас для выхода за границу образца отвечают layer_index = -1 (для выхода в одно сторону) -2 (в другую)
Наткнулся на ошибку, что границу текущего слоя или свойства определял z_start_table[layer_index], т.е. не слой воздуха, а последний слой образца....

Как фиксить?

Есть вариант расширить таблицы свойств, который класс образца возвращает.
Ну и сам layer_index будет при 3 образцах принимать значения 0 - воздух, 1, 2, 3 - слои образца, 4 - воздух

Либо можно оставить как было, просто вовремя проверять на выход и ассерты написать в том месте где хочу свойства текущих слоев вытаскивать

**Comment by NikomSol** [comment]
Добавлять новые слои решил, что не вариант, сложно отслеживать вылет за границу (в некоторых функциях просто нет информации о том, сколько всего слоев в образце, т.е. не понятно при каком условии ты попал в воздух)
Оставлять -1 и -2 тоже решил, что не стоит, в numba асерты не попилишь

Решил вылет в воздух выделить, как np.NINF, np.PINF

**Comment by VulpesCorsac** [comment]
Вообще это действительно оптимальный варант, потом будет понятно почему, когда можно будет переписывать поиск слоя на более быстрый алгоритм
