### ISSUE TITLE
Не соответсвуют гит и локальная директория

### ISSUE THREAD

**Issue by NikomSol** [NikomSol/MCML-Integrating-Sphere#20]
Я вижу папку на гите, но она не подгружается мне на комп
tests/detector

**Comment by VulpesCorsac** [comment]
Это очень странно, признаю, будем разбираться тогда. Возможно локальному клиенту поплохело от того, что есть tests и Tests

**Comment by NikomSol** [comment]
Если в названии папки только регистр менять, он это не воспринимает, как изменение (не предлагает коммитить)
Если что-то еще поменять, то уже воспринимает, так что можно в два шага переименовать на нижний регистр

**Comment by VulpesCorsac** [comment]
Вообще это забавно немного, я такого не ожидал. Но раз так, то, так понимаю, вопрос закрыт
