### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by NikomSol** [NikomSol/MCML-Integrating-Sphere#3]
Начал писать, но это "Г", как правильно?

**Comment by VulpesCorsac** [comment]
1) Переезжаем на pytest
2) В идеале проверяем каждую функцию на то, что она работает ожидаемым образом (:

**Comment by NikomSol** [comment]
3. Т.е. это нормально в одном тесте по 15 проверок одной функции делать с разными входными данными?
Будет понятно на каких фейл произошел?
4. Не прошло и дня как я поменял функцию, так чтобы у нее поменялся выход)
Полагаю смысла обкладывать тестами то, что может поменяться в ближайшее время?

**Comment by VulpesCorsac** [comment]
> 3. Т.е. это нормально в одном тесте по 15 проверок одной функции делать с разными входными данными?
>    Будет понятно на каких фейл произошел?
> 4. Не прошло и дня как я поменял функцию, так чтобы у нее поменялся выход)
>    Полагаю смысла обкладывать тестами то, что может поменяться в ближайшее время?

3. Да, pytest это показывает, попробуй что-то сломать и запустить
4. Да, на самом деле есть такое. Я просто переписал те тесты, которые уже были чуть красивее, но пока, если они мешают, лучше их вообще убрать
