### ISSUE TITLE
Обращение к глобальным переменным

### ISSUE THREAD

**Issue by NikomSol** [NikomSol/MCML-Integrating-Sphere#4]
На примере get_func_gauss_distribution при создании функции использую глобальные параметры, к ним же обращение идет только при создании?

**Comment by VulpesCorsac** [comment]
Если ты про x0 и т.д. - нет, кажется, их создание происходит каждый раз

**Comment by NikomSol** [comment]
Проверил, таки один раз
Вот такая же конструкция, при вызове bugaga() создается x0 единожды, и выход buf всегда одинаковый получается.

def bugaga():
    x0 = np.random.rand()
    @njit(fastmath=True)
    def buf(i):
        return x0
    return buf

loc_buf = bugaga()
result = map(loc_buf, range(5))
print(list(result))
